feat: 서버-클라이언트 연동 및 게임 프로세스 스캔 기능 구현
- Spring Security 의존성을 제거하여 API 인증 문제 해결

- MySQL 데이터베이스 연동 및 data.sql 스크립트 실행 설정 추가

- JavaFX 클라이언트에서 실행 중인 게임 프로세스를 주기적으로 스캔

- 스캔 상태에 따라 UI 메시지를 동적으로 변경

diff --git a/client/build/scripts/client b/client/build/scripts/client
--- a/client/build/scripts/client
+++ b/client/build/scripts/client
@@ -15,8 +15,6 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
-# SPDX-License-Identifier: Apache-2.0
-#
 
 ##############################################################################
 #
@@ -57,7 +55,7 @@
 #       Darwin, MinGW, and NonStop.
 #
 #   (3) This script is generated from the Groovy template
-#       https://github.com/gradle/gradle/blob/HEAD/platforms/jvm/plugins-application/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
+#       https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt
 #       within the Gradle project.
 #
 #       You can find Gradle at https://github.com/gradle/gradle/.
@@ -82,11 +80,13 @@ do
     esac
 done
 
-# This is normally unused
-# shellcheck disable=SC2034
+APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit
+
+APP_NAME="client"
 APP_BASE_NAME=${0##*/}
-# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
-APP_HOME=$( cd -P "${APP_HOME:-./}.." > /dev/null && printf '%s\n' "$PWD" ) || exit
+
+# Add default JVM options here. You can also use JAVA_OPTS and CLIENT_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS=""
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -114,7 +114,7 @@ case "$( uname )" in                #(
   NONSTOP* )        nonstop=true ;;
 esac
 
-CLASSPATH=$APP_HOME/lib/client-0.1.0-SNAPSHOT.jar:$APP_HOME/lib/javafx-controls-21.0.1-win.jar:$APP_HOME/lib/javafx-graphics-21.0.1-win.jar:$APP_HOME/lib/oshi-core-6.4.4.jar:$APP_HOME/lib/javafx-base-21.0.1-win.jar:$APP_HOME/lib/jna-platform-5.13.0.jar:$APP_HOME/lib/jna-5.13.0.jar:$APP_HOME/lib/slf4j-api-2.0.7.jar
+CLASSPATH=$APP_HOME/lib/client-0.1.0-SNAPSHOT.jar:$APP_HOME/lib/javafx-fxml-17-mac-aarch64.jar:$APP_HOME/lib/javafx-controls-17-mac-aarch64.jar:$APP_HOME/lib/okhttp-4.12.0.jar:$APP_HOME/lib/jackson-annotations-2.16.1.jar:$APP_HOME/lib/jackson-core-2.16.1.jar:$APP_HOME/lib/jackson-databind-2.16.1.jar:$APP_HOME/lib/logback-classic-1.4.14.jar:$APP_HOME/lib/javafx-graphics-17-mac-aarch64.jar:$APP_HOME/lib/okio-jvm-3.6.0.jar:$APP_HOME/lib/kotlin-stdlib-jdk8-1.9.10.jar:$APP_HOME/lib/logback-core-1.4.14.jar:$APP_HOME/lib/slf4j-api-2.0.7.jar:$APP_HOME/lib/javafx-base-17-mac-aarch64.jar:$APP_HOME/lib/kotlin-stdlib-jdk7-1.9.10.jar:$APP_HOME/lib/kotlin-stdlib-1.9.10.jar:$APP_HOME/lib/kotlin-stdlib-common-1.9.10.jar:$APP_HOME/lib/annotations-13.0.jar
 
 
 # Determine the Java command to use to start the JVM.
@@ -133,29 +133,22 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    if ! command -v java >/dev/null 2>&1
-    then
-        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
-    fi
 fi
 
 # Increase the maximum file descriptors if we can.
 if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
     case $MAX_FD in #(
       max*)
-        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
         MAX_FD=$( ulimit -H -n ) ||
             warn "Could not query maximum file descriptor limit"
     esac
     case $MAX_FD in  #(
       '' | soft) :;; #(
       *)
-        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
-        # shellcheck disable=SC2039,SC3045
         ulimit -n "$MAX_FD" ||
             warn "Could not set maximum file descriptor limit to $MAX_FD"
     esac
@@ -200,15 +193,11 @@ if "$cygwin" || "$msys" ; then
     done
 fi
 
-
-# Add default JVM options here. You can also use JAVA_OPTS and CLIENT_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS=""
-
-# Collect all arguments for the java command:
-#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and optsEnvironmentVar are not allowed to contain shell fragments,
-#     and any embedded shellness will be escaped.
-#   * For example: A user cannot expect ${Hostname} to be expanded, as it is an environment variable and will be
-#     treated as '${Hostname}' itself on the command line.
+# Collect all arguments for the java command;
+#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $CLIENT_OPTS can contain fragments of
+#     shell script including quotes and variable substitutions, so put them in
+#     double quotes to make sure that they get re-expanded; and
+#   * put everything else in single quotes, so that it's not re-expanded.
 
 set -- \
         -classpath "$CLASSPATH" \
